Vagrant.configure("2") do |config|
    #config.proxy.http = "http://webproxy.wlb2.nam.nsroot.net:8080"
    #config.proxy.https = "http://webproxy.wlb2.nam.nsroot.net:8080"
    #config.vm.box = "boxcutter/centos66"
    #config.vm.box = "boxcutter/centos64-i386"
    #config.vm.provision "file", source: "~/IHS.zip", destination: "/tmp/IHS.zip"
    #config.vm.network :forwarded_port, guest: 2000, host: 4567
    config.berkshelf.enabled = true
    config.vm.provision :chef_solo do |chef|
        chef.add_recipe "ems-install"
				chef.add_recipe "ems-createinstance"
    end
end
