name 'bw-install'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bw-install'
long_description 'Installs/Configures bw-install'
version '0.1.0'
